### ISSUE TITLE
Updating src/INTERNALS.overview

### ISSUE THREAD

**Issue by pluto439** [david-schmidt/gsport#1]
Asking people what each file is for is something I've done for quite some time, and kegs is the first program I've met that actually describes it. Too bad it wasn't updated in the last 13 years.

**Comment by david-schmidt** [comment]
There is a little more developer-oriented detail on this page:
https://david-schmidt.github.io/gsport/developing.html

**Comment by pluto439** [comment]
It's not even close, it just says how to compile it.

Can somebody explain what the atbridge folder is for? Or should I stare blankly at it and open files randomly for a hour to figure it out, like I usually have to do?

Or at least delete it, it's very outdated anyway. Nobody writes documentation nowadays, nobody knows how it should look like.

**Comment by pluto439** [comment]
Why was this closed?

**Comment by david-schmidt** [comment]
Because I don't have an answer for you.  Unless you're volunteering to work on it...?

**Comment by pluto439** [comment]
I actually want to clean it up a bit. Changing crossplatform macros, and move from cygwin to mingw. And maybe even creating a little windows-only fork which throws out all crossplatform functionality, just to simplify building process.

I'm afraid of touching those folders though, I don't know what's in them.

**Comment by david-schmidt** [comment]
By all means - fork away and submit PRs.  If you don't know what something does - it's probably best not to amputate it, but instead concentrate on those things you **do** know and interest you.

**Comment by pneubauer** [comment]
ATBridge is the AppleTalk bridge.  The atbridge.h file contains high-level documentation describing this.  The "docs" directory contains user-level documentation.
