### ISSUE TITLE
How to play an Apple IIgs game on the GSport emulator

### ISSUE THREAD

**Issue by morykwas** [david-schmidt/gsport#17]
I had an Apple IIgs computer many years ago.  My family loved playing a game called "Plunder!"  So now I'm trying to run it on my Windows 10 PC, using the GSport emulator.

I think I'm on the right track.  The screen looks like a IIgs startup screen with a BASIC prompt.  I've downloaded a file named Plunder.2mg but I just don't know what to do with it.

Can anyone please help me?
Thanks!

![GSport](https://user-images.githubusercontent.com/130001593/230218656-a055f74e-0423-49b9-8aee-b60eec2d3fc2.png)

**Comment by david-schmidt** [comment]
Well, you got most of the way there!  Congratulations are in order for sure.  So, on the one hand - mounting a floppy is as easy as dragging the .2mg disk over to the blue screen, dropping it, and typing PR#5.  Unfortunately, on the other hand - the game you selected doesn't run all by itself, it depends on the entire GSOS operating system to be underneath it, which they don't provide.  You will need to get familiar with the way GSport (and KEGS, from which it descended) deals with disks to mount.  It helps to have lived through the 90s, but F4 brings up the configuration menu - and from there, you will need to mount a GSOS operating system (from the same place you got your game, I imagine, whatistheiigs) in one of the hard drive slots in slot 7, and then mount your game in slot 5 and boot GSOS (PR#7).  That will put the floppy on the GSOS desktop, and you'll be able to double-click on it to open up the disk and the game.

This page has some details about how to operate the configuration menu system:
https://david-schmidt.github.io/gsport/operating.html

**Comment by morykwas** [comment]
Thanks, David, for your prompt and clear response.  That's exactly the information I needed, and the game is working perfectly now!  My family and I really appreciate your help.  --Ed

![plunder](https://user-images.githubusercontent.com/130001593/230364148-3d54883c-2449-4653-a40a-44988b149178.png)

**Comment by pacpir** [comment]
David:
Do you think you could make s short youtube video on how to get either
GSPORT or KEGS or any of the Apple II emulators working on Steam?  I think
with the Proton it would be a simple video so that allt he Apple IIGS
enthusiasts can do it and use ther STEAM DECK to pay those games?

Thanks,

Perry

**Comment by david-schmidt** [comment]
Sorry, no - I don't know the first thing about Steam.
