### ISSUE TITLE
windows CLI -config

### ISSUE THREAD

**Issue by Vikinge** [david-schmidt/gsport#18]
Can anyone confirm if the windows CLI -config is still supported?   I want to prebuild specific config files for GS Boot setups, but every attempt shows bad option: -config.  This option is listed in the manual.

**Comment by david-schmidt** [comment]
Not that I'm aware of... where are you seeing this "manual?"  The doco for command line options (https://david-schmidt.github.io/gsport/operating.html#GSport_command-line_option_summary) doesn't list it...

**Comment by Vikinge** [comment]
I read in a GSport 0.14 manual https://github.com/digarok/gsplus/blob/master/doc/gsplusmanual.pdf, page 12.  Is there any other way to have multiple config files that can open per cli?

**Comment by david-schmidt** [comment]
Ah, that is GSPlus, not GSport; you’ll need to ask over there.
