### ISSUE TITLE
gsportx doesn't work on Raspberry Pi 3 B+ with Raspbian (Debian 9.4)

### ISSUE THREAD

**Issue by Arakula** [david-schmidt/gsport#4]
The frame buffer version works, but the X Windows version dies with a memory access error.
Here's what happens:

pi@pidrei:/usr/bin $ gsportx
Trying 'config.txt'
Trying 'config.gsport'
Trying 'gsport_conf'
Trying '.config.gsport'
Trying './config.txt'
Trying './config.gsport'
Trying './gsport_conf'
Trying './.config.gsport'
Trying '/home/pi/config.txt'
Trying '/home/pi/config.gsport'
Trying '/home/pi/gsport_conf'
Trying '/home/pi/.config.gsport'
Trying '/usr/bin/config.txt'
Trying '/usr/bin/config.gsport'
Trying '/usr/bin/gsport_conf'
Trying '/usr/bin/.config.gsport'
Trying '/home/pi/Library/GSport/config.txt'
Trying '/home/pi/Library/GSport/config.gsport'
Trying '/home/pi/Library/GSport/gsport_conf'
Trying '/home/pi/Library/GSport/.config.gsport'
Trying './/Contents/Resources/config.txt'
Trying './/Contents/Resources/config.gsport'
Trying './/Contents/Resources/gsport_conf'
Trying './/Contents/Resources/.config.gsport'
Trying '/usr/local/lib/config.txt'
Trying '/usr/local/lib/config.gsport'
Trying '/usr/local/lib/gsport_conf'
Trying '/usr/local/lib/.config.gsport'
Trying '/usr/local/gsport/config.txt'
Trying '/usr/local/gsport/config.gsport'
Trying '/usr/local/gsport/gsport_conf'
Trying '/usr/local/gsport/.config.gsport'
Trying '/usr/local/lib/gsport/config.txt'
Trying '/usr/local/lib/gsport/config.gsport'
Trying '/usr/local/lib/gsport/gsport_conf'
Trying '/usr/local/lib/gsport/.config.gsport'
Trying '/usr/share/gsport/config.txt'
Parsing configuration file
Image named /usr/share/gsport/disks/GSport Internet Starter Kit.2mg is in 2IMG format
...parse_option: line 11, 0x6e6e0,0x6e6e0 = g_joystick_type = 0 (g_joystick_type = 0) len:19
...parse_option: line 12, 0x6e6e0,0x6e6e0 = g_ethernet = 1 (g_ethernet = 1) len:14
...parse_option: line 13, 0x6e6e0,0x6e6e0 = g_limit_speed = 3 (g_limit_speed = 3) len:17
Using host ethernet interface: wlan0
Uthernet support is ON.
CS8900a rev.D reset
Read: 262144 bytes of ROM
Patching ROM 03 smartport bug
RAM size is 0 - 900000 (9.00MB)
Preparing X Windows graphics system
Visual 0
	id: 00000021, screen: 0, depth: 24, class: 4
	red: 00ff0000, green: 0000ff00, blue: 000000ff
	cmap size: 256, bits_per_rgb: 8
Chose visual: 0, max_colors: -1
Will use shared memory for X
Memory access error (or whatever the English version reports, in German, it's "Speicherzugriffsfehler").

Before the error, a window shortly shows up, but goes away instantly.

**Comment by Arakula** [comment]
OK, I know why it happens ...
the error occurs in src/xdriver.c in line 618:
new_gc.font = g_text_FontSt->fid;
... kaboom, since g_text_FontSt is a nil pointer.

The problem is with the font "8x13" which is hidden behind the preprocessor constant FONT_NAME_STATUS.
The lines:
        font_ptr = XListFonts(g_display, FONT_NAME_STATUS, 4, &cnt);
and
        g_text_FontSt = XLoadQueryFont(g_display, FONT_NAME_STATUS);
both return nil pointers.

Unfortunately, I don't know enough about the X Window system and/or Raspbian to suggest a solution. Maybe it's a simple "Ah yes, install package xxx", or "Ah yes, change the line reading xxx in file yyy to zzz", but I don't know. Help ...?

**Comment by Arakula** [comment]
(Didn't intend to close the issue, clicked the wrong button)

**Comment by Arakula** [comment]
OK ... one of the following things did the trick

sudo apt-get install xfonts-scalable
sudo dpkg-reconfigure fontconfig-config
sudo dpkg-reconfigure fontconfig

Unfortunately, I wasn't clever enough to log out and in between the steps, so I can't tell which <sigh>...
anyway, it works now.

**Comment by bobbimanners** [comment]
I just ran into this issue on Raspbian (Raspberry Pi 4).  It seems the fix is to change the font to "fixed" in xdriver.c, around line 45:

```
// #define FONT_NAME_STATUS      "8x13"
#define FONT_NAME_STATUS        "fixed"
```

**Comment by BrianHoldsworth** [comment]
Same issue Arch Linux x86_64. Using "fixed" for font name solves.
